baseURL = "/"
languageCode = "en-us"
title = "Grieving Sleep"
theme = "hyde"
relativeUrls = true

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "A journey of sleeplessness"
    github = "https://github.com/musicionary"
    twitter = "https://twitter.com/musicionary"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"
    themeColor = "theme-base-0g"
    copyright = "Chip Carnes"

[Permalinks]
    post = "/:filename/"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/musicionary/"},
      {Name = "Goodreads", URL = "https://www.goodreads.com/user/show/7984451-chip-carnes"}
  ]

