baseURL = "/"
languageCode = "en-us"
title = "Unified Theory"
theme = "hyde"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "Building a unified theory of some things"
    github = "https://github.com/musicionary"
    twitter = "https://twitter.com/musicionary"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"
    themeColor = "theme-base-0g"

[Permalinks]
    post = "/:filename/"

