baseURL = "/"
languageCode = "en-us"
title = "Unified Theory"
theme = "hyde"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "Building a unified theory of some things"
    github = "https://github.com/musicionary"
    twitter = "https://twitter.com/musicionary"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"
    themeColor = "theme-base-0g"

[Permalinks]
    post = "/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
